### ISSUE TITLE
Advertise GitHub action: perl-actions/install-with-cpm

### ISSUE THREAD

**Issue by atoomic** [skaji/cpm#170]
This is a dummy and early prototype but the idea is to easily get cpm available in a GitHub workflow using `perl-actions/install-cpm`

You can view more: https://github.com/marketplace/actions/install-cpm

Sample usage:
```yaml
uses: perl-actions/install-cpm@v1.0
run: |
   sudo cpm install -g Module::To::Install
```

Maybe I can see in the future adding parameters like cpanfile or list of modules so they are installed?

**Comment by skaji** [comment]
Cool!

**Comment by atoomic** [comment]
I've improved it to now take multiple arguments so you can write something like this

```yaml
- name: install cpm and one module
  uses: perl-actions/install-cpm@v1.1
  with:
    install: 'Simple::Accessor'
```

```yaml
- name: install cpm and multiple modules
  uses: perl-actions/install-cpm@v1.1
  with:
      install: |
        Simple::Accessor
        Test::Parallel
```

```yaml
- name: install cpm and files from cpanfile
  uses: perl-actions/install-cpm@v1.1
  with:
      install: 'Simple::Accessor'
      global: false
      sudo: false
```

....
view the link above for more examples
